    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Basket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class BasketPersistenceDbContextDesignTimeFactory : IDesignTimeDbContextFactory<BasketPersistenceDbContext>
{
    public BasketPersistenceDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<BasketPersistenceDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=localhost;Database=teck_migrations;User=root;Password=root;";
        optionsBuilder.UseMySQL(connectionString, b => b.MigrationsAssembly("Basket.Infrastructure.Migrations.MySql"));

        return new BasketPersistenceDbContext(optionsBuilder.Options);
    }
}
