apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-gateway-config
data:
  Keycloak__realm: Teck.Cloud.Dev
  Keycloak__auth-server-url: https://auth.tecklab.dk/
  Keycloak__ssl-required: none
  Keycloak__resource: teck-admin-gateway
  Keycloak__use-resource-role-mappings: "true"
  Keycloak__confidential-port: "0"
  ReverseProxy__Clusters__catalog__Destinations__Default__Address: http://catalog-api
  ReverseProxy__Clusters__customer__Destinations__Default__Address: http://customer-api
