apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: admin-gateway
          image: ghcr.io/teck-lab/teck-cloud/web-admin-gateway:preview
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: admin-gateway-config
            - secretRef:
                name: admin-gateway-keycloak
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
