apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: customer-api
      app.kubernetes.io/component: database-migration
    includeSelectors: false
resources:
  - job.postgres.yaml
