    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Product.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class ProductWriteDbContextDesignTimeFactory : IDesignTimeDbContextFactory<ProductWriteDbContext>
{
    public ProductWriteDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<ProductWriteDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=localhost;Database=teck_migrations;User=root;Password=root;";
        optionsBuilder.UseMySQL(connectionString, b => b.MigrationsAssembly("Teck.Cloud.Migrations.MySql"));

        return new ProductWriteDbContext(optionsBuilder.Options);
    }
}
