apiVersion: v1
kind: ConfigMap
metadata:
  name: yarp-gateway-config
data:
  Services__CatalogApi__Url: http://catalog-api
  Services__CustomerApi__Url: http://customer-api
  ReverseProxy__Clusters__catalog__Destinations__Default__Address: http://catalog-api
  ReverseProxy__Clusters__customer__Destinations__Default__Address: http://customer-api
  ConnectionStrings__redis: >-
    redis-shared-s-hl.redis-system.svc.cluster.local:26379,serviceName=mymaster,abortConnect=false
