    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class BillingWriteDbContextDesignTimeFactory : IDesignTimeDbContextFactory<BillingDbContext>
{
    public BillingDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<BillingDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Host=localhost;Database=teck_migrations;Username=postgres;Password=postgres;";
        optionsBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly("Teck.Cloud.Migrations.PostgreSQL"));

        return new BillingDbContext(optionsBuilder.Options);
    }
}
