    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Order.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class OrderPersistenceDbContextDesignTimeFactory : IDesignTimeDbContextFactory<OrderPersistenceDbContext>
{
    public OrderPersistenceDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<OrderPersistenceDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Host=localhost;Database=teck_migrations;Username=postgres;Password=postgres";
        optionsBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly("Order.Infrastructure.Migrations.PostgreSQL"));

        return new OrderPersistenceDbContext(optionsBuilder.Options);
    }
}
