apiVersion: v1
kind: Service
metadata:
  name: yarp-gateway
spec:
  selector:
    app.kubernetes.io/name: yarp-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP