    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Customer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class CustomerWriteDbContextDesignTimeFactory : IDesignTimeDbContextFactory<CustomerWriteDbContext>
{
    public CustomerWriteDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<CustomerWriteDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=localhost;Database=teck_migrations;User=root;Password=root;";
        optionsBuilder.UseMySQL(connectionString, b => b.MigrationsAssembly("Customer.Infrastructure.Migrations.MySql"));

        return new CustomerWriteDbContext(optionsBuilder.Options);
    }
}
