apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  immutable: true
  labels:
    app.kubernetes.io/name: catalog-api
    app.kubernetes.io/component: database-migration
resources:
  - job.postgres.yaml
configMapGenerator:
  - name: catalog-api-flyway-postgres-sql
    files:
      - V20260303203156__InitialPostgreSQL.sql=./postgres/V20260303203156__InitialPostgreSQL.sql

