    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class ApplicationWriteDbContextDesignTimeFactory : IDesignTimeDbContextFactory<ApplicationWriteDbContext>
{
    public ApplicationWriteDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<ApplicationWriteDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=(localdb)\\\\mssqllocaldb;Database=TeckCloudMigrations;Trusted_Connection=true;MultipleActiveResultSets=true;";
        optionsBuilder.UseSqlServer(connectionString, b => b.MigrationsAssembly("Catalog.Infrastructure.Migrations.SqlServer"));

        return new ApplicationWriteDbContext(optionsBuilder.Options);
    }
}
