apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../database/migrations
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: ghcr.io/teck-lab/teck-cloud-migrations
    newTag: development
  - name: ghcr.io/teck-lab/teck-cloud/customer
    newTag: development
