    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Location.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class TemplateFontMetadataDbContextDesignTimeFactory : IDesignTimeDbContextFactory<TemplateFontMetadataDbContext>
{
    public TemplateFontMetadataDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<TemplateFontMetadataDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=(localdb)\\\\mssqllocaldb;Database=TeckCloudMigrations;Trusted_Connection=true;MultipleActiveResultSets=true;";
        optionsBuilder.UseSqlServer(connectionString, b => b.MigrationsAssembly("Teck.Cloud.Migrations.SqlServer"));

        return new TemplateFontMetadataDbContext(optionsBuilder.Options, tenantAccessor: null);
    }
}
