    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Order.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class OrderPersistenceDbContextDesignTimeFactory : IDesignTimeDbContextFactory<OrderPersistenceDbContext>
{
    public OrderPersistenceDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<OrderPersistenceDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Server=(localdb)\\\\mssqllocaldb;Database=TeckCloudMigrations;Trusted_Connection=true;MultipleActiveResultSets=true;";
        optionsBuilder.UseSqlServer(connectionString, b => b.MigrationsAssembly("Order.Infrastructure.Migrations.SqlServer"));

        return new OrderPersistenceDbContext(optionsBuilder.Options);
    }
}
