apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregate-gateway-config
data:
  Logging__LogLevel__Default: Information
  Logging__LogLevel__Microsoft.AspNetCore: Warning
  Keycloak__realm: Teck.Cloud.Dev
  Keycloak__auth-server-url: https://auth.tecklab.dk/
  Keycloak__ssl-required: none
  Keycloak__resource: aggregate-gateway
  Keycloak__use-resource-role-mappings: "true"
  Keycloak__confidential-port: "0"
  Services__CatalogApi__Url: http://catalog-api
  Services__CustomerApi__Url: http://customer-api
  ConnectionStrings__redis: preview-redis:6379,abortConnect=false