    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class ApplicationWriteDbContextDesignTimeFactory : IDesignTimeDbContextFactory<ApplicationWriteDbContext>
{
    public ApplicationWriteDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<ApplicationWriteDbContext>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "Host=localhost;Database=teck_migrations;Username=postgres;Password=postgres";
        optionsBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly("Catalog.Infrastructure.Migrations.PostgreSQL"));

        return new ApplicationWriteDbContext(optionsBuilder.Options);
    }
}
