# Remove-Migration.ps1
# Remove the latest EF Core migration from provider-specific migration projects per service.

param (
    [Parameter(Mandatory = $true)]
    [string]$ServiceName,

    [Parameter(Mandatory = $false)]
    [switch]$ChangeToSolutionDir,

    [Parameter(Mandatory = $false)]
    [string[]]$Providers = @("postgres", "sqlserver", "mysql")
)

if ($ChangeToSolutionDir -or -not $PSBoundParameters.ContainsKey('ChangeToSolutionDir')) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $solutionDir = Resolve-Path (Join-Path $scriptDir "..\..")
    Set-Location $solutionDir
    Write-Host "Working directory set to: $solutionDir" -ForegroundColor Cyan
}

$solutionFile = "Teck.Cloud.slnx"

$providerConfigs = @{
    "postgres" = @{
        DisplayName = "PostgreSQL"
        FolderSuffix = "PostgreSQL"
        ServerType = "postgres"
        DefaultConnectionString = "Host=localhost;Database=teck_migrations;Username=postgres;Password=postgres"
    }
    "sqlserver" = @{
        DisplayName = "SQL Server"
        FolderSuffix = "SqlServer"
        ServerType = "sqlserver"
        DefaultConnectionString = "Server=(localdb)\mssqllocaldb;Database=TeckCloudMigrations;Trusted_Connection=true;MultipleActiveResultSets=true;"
    }
    "mysql" = @{
        DisplayName = "MySQL"
        FolderSuffix = "MySql"
        ServerType = "mysql"
        DefaultConnectionString = "Server=localhost;Database=teck_migrations;User=root;Password=root;"
    }
}

$serviceMap = @{
    "catalog" = @{
        StartupProject = "src/services/catalog/Catalog.Infrastructure/Catalog.Infrastructure.csproj"
        InfrastructureProject = "src/services/catalog/Catalog.Infrastructure/Catalog.Infrastructure.csproj"
        WriteContextType = "Catalog.Infrastructure.Persistence.ApplicationWriteDbContext"
        MigrationProjectPrefix = "src/services/catalog/Catalog.Infrastructure.Migrations"
    }
    "customer" = @{
        StartupProject = "src/services/customer/Customer.Infrastructure/Customer.Infrastructure.csproj"
        InfrastructureProject = "src/services/customer/Customer.Infrastructure/Customer.Infrastructure.csproj"
        WriteContextType = "Customer.Infrastructure.Persistence.CustomerWriteDbContext"
        MigrationProjectPrefix = "src/services/customer/Customer.Infrastructure.Migrations"
    }
}

function Ensure-MigrationProject {
    param(
        [hashtable]$Service,
        [hashtable]$ProviderConfig
    )

    $projectPath = "$($Service.MigrationProjectPrefix).$($ProviderConfig.FolderSuffix)/$([IO.Path]::GetFileName("$($Service.MigrationProjectPrefix).$($ProviderConfig.FolderSuffix)"))" + ".csproj"

    $contextType = $Service.WriteContextType
    $contextNamespace = $contextType.Substring(0, $contextType.LastIndexOf('.'))
    $contextTypeName = $contextType.Substring($contextType.LastIndexOf('.') + 1)

    function Ensure-DesignTimeFactory {
        param(
            [string]$ProjectDir,
            [string]$ContextNamespace,
            [string]$ContextTypeName,
            [hashtable]$ProviderConfig
        )

        $factoryDir = Join-Path $ProjectDir "DesignTime"
        New-Item -ItemType Directory -Path $factoryDir -Force | Out-Null
        $legacyFactoryPath = Join-Path $factoryDir "$($ContextTypeName)DesignTimeFactory.cs"
        $factoryPath = Join-Path $factoryDir "$($ContextTypeName)DesignTimeFactory.g.cs"
        Remove-Item $legacyFactoryPath -ErrorAction SilentlyContinue

        $defaultConnection = ($ProviderConfig.DefaultConnectionString -replace '\\', '\\\\').Replace('"', '`"')
        $migrationAssemblyName = [IO.Path]::GetFileName($ProjectDir)
        $providerOptionsLine = switch ($ProviderConfig.ServerType) {
            'postgres' { "optionsBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly(`"$migrationAssemblyName`"));" }
            'sqlserver' { "optionsBuilder.UseSqlServer(connectionString, b => b.MigrationsAssembly(`"$migrationAssemblyName`"));" }
            default { "optionsBuilder.UseMySQL(connectionString, b => b.MigrationsAssembly(`"$migrationAssemblyName`"));" }
        }

        $factoryContent = @"
    // <auto-generated />
    #pragma warning disable SA1633,SA1515,CS1591

using $ContextNamespace;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace MigrationProject.DesignTime;

public sealed class $($ContextTypeName)DesignTimeFactory : IDesignTimeDbContextFactory<$ContextTypeName>
{
    public $ContextTypeName CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<$ContextTypeName>();
        var connectionString = Environment.GetEnvironmentVariable("MIGRATION_CONNECTION_STRING") ?? "$defaultConnection";
        $providerOptionsLine

        return new $ContextTypeName(optionsBuilder.Options);
    }
}
"@

    Set-Content -Path $factoryPath -Value $factoryContent
    }

    if (Test-Path $projectPath) {
        $projectDir = Split-Path $projectPath -Parent
        Ensure-DesignTimeFactory -ProjectDir $projectDir -ContextNamespace $contextNamespace -ContextTypeName $contextTypeName -ProviderConfig $ProviderConfig
        return $projectPath
    }

    $projectDir = Split-Path $projectPath -Parent
    New-Item -ItemType Directory -Path $projectDir -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $projectDir "Persistence\Migrations") -Force | Out-Null

    $infraAbsolute = (Resolve-Path $Service.InfrastructureProject).Path
    $projectAbsoluteDir = (Resolve-Path $projectDir).Path
    $relativeInfrastructurePath = [IO.Path]::GetRelativePath($projectAbsoluteDir, $infraAbsolute).Replace('/', '\\')

    $projectContent = @"
<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);S1186</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=""Microsoft.EntityFrameworkCore.Design"">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include=""$relativeInfrastructurePath"" />
  </ItemGroup>

</Project>
"@

    Set-Content -Path $projectPath -Value $projectContent -NoNewline
    Write-Host "Created migration project: $projectPath" -ForegroundColor Green

    Ensure-DesignTimeFactory -ProjectDir $projectDir -ContextNamespace $contextNamespace -ContextTypeName $contextTypeName -ProviderConfig $ProviderConfig

    if (Test-Path $solutionFile) {
        $solutionContent = Get-Content $solutionFile -Raw
        if ($solutionContent -notmatch [Regex]::Escape($projectPath)) {
            dotnet sln $solutionFile add $projectPath | Out-Null
            Write-Host "Added project to solution: $projectPath" -ForegroundColor Green
        }
    }

    return $projectPath
}

$serviceKey = $ServiceName.ToLowerInvariant()
if (-not $serviceMap.ContainsKey($serviceKey)) {
    Write-Error "Unsupported service '$ServiceName'. Valid services: $($serviceMap.Keys -join ', ')"
    exit 1
}

$service = $serviceMap[$serviceKey]
$contextType = $service.WriteContextType

Write-Host "=== Multi-Provider Migration Removal (Separate Projects) ===" -ForegroundColor Magenta
Write-Host "Service: $ServiceName" -ForegroundColor Cyan
Write-Host "Providers: $($Providers -join ', ')" -ForegroundColor Cyan
Write-Host "Startup project: $($service.StartupProject)" -ForegroundColor Gray
Write-Host "DbContext type: $contextType" -ForegroundColor Gray
Write-Host "" -ForegroundColor Gray

$successfulRemovals = @()
$failedRemovals = @()

foreach ($provider in $Providers) {
    if (-not $providerConfigs.ContainsKey($provider)) {
        Write-Warning "Unknown provider '$provider'. Skipping. Valid providers are: $($providerConfigs.Keys -join ', ')"
        continue
    }

    $providerConfig = $providerConfigs[$provider]
    $providerDisplayName = $providerConfig.DisplayName

    Write-Host "--- Removing migration for $providerDisplayName ---" -ForegroundColor Yellow

    $migrationProject = Ensure-MigrationProject -Service $service -ProviderConfig $providerConfig
    $migrationProjectDir = Split-Path $migrationProject -Parent
    $migrationsDir = Join-Path $migrationProjectDir "Persistence\Migrations"

    if (-not (Test-Path $migrationsDir)) {
        Write-Host "No migration directory found for $providerDisplayName. Skipping." -ForegroundColor DarkYellow
        $successfulRemovals += "$providerDisplayName (no-op)"
        Write-Host "" -ForegroundColor Gray
        continue
    }

    $latestMigration = Get-ChildItem -Path $migrationsDir -Filter "*.cs" -File |
        Where-Object { $_.Name -notlike "*.Designer.cs" -and $_.Name -notlike "*ModelSnapshot.cs" } |
        Sort-Object Name -Descending |
        Select-Object -First 1

    if ($null -eq $latestMigration) {
        Write-Host "No migration file found for $providerDisplayName. Skipping." -ForegroundColor DarkYellow
        $successfulRemovals += "$providerDisplayName (no-op)"
        Write-Host "" -ForegroundColor Gray
        continue
    }

    $env:MIGRATION_DB_PROVIDER = $provider
    $env:MIGRATION_CONNECTION_STRING = $providerConfig.DefaultConnectionString
    $env:MIGRATION_SERVER_TYPE = $providerConfig.ServerType
    Remove-Item env:MIGRATION_ASSEMBLY -ErrorAction SilentlyContinue

    $dotnetEfCommand = "dotnet ef migrations remove --force " +
        "--startup-project `"$migrationProject`" " +
        "--project `"$migrationProject`" " +
        "--context $contextType"

    Write-Host "Executing: $dotnetEfCommand" -ForegroundColor Gray
    $removeOutput = Invoke-Expression $dotnetEfCommand 2>&1 | Out-String

    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ $providerDisplayName migration removed successfully" -ForegroundColor Green
        $successfulRemovals += "$providerDisplayName ($migrationProject)"
    }
    else {
        if ($removeOutput -match "No ModelSnapshot was found") {
            $latestMigrationBase = [IO.Path]::GetFileNameWithoutExtension($latestMigration.Name)
            $latestDesigner = Join-Path $migrationsDir ($latestMigrationBase + ".Designer.cs")

            Remove-Item $latestMigration.FullName -Force -ErrorAction SilentlyContinue
            Remove-Item $latestDesigner -Force -ErrorAction SilentlyContinue

            Write-Host "⚠️ EF remove reported missing snapshot; removed orphan migration files via script fallback for $providerDisplayName." -ForegroundColor DarkYellow
            $successfulRemovals += "$providerDisplayName ($migrationProject) [fallback-no-snapshot]"
        }
        else {
            Write-Host "❌ Failed to remove $providerDisplayName migration" -ForegroundColor Red
            $failedRemovals += "$providerDisplayName"
        }
    }

    Remove-Item env:MIGRATION_DB_PROVIDER -ErrorAction SilentlyContinue
    Remove-Item env:MIGRATION_CONNECTION_STRING -ErrorAction SilentlyContinue
    Remove-Item env:MIGRATION_SERVER_TYPE -ErrorAction SilentlyContinue

    Write-Host "" -ForegroundColor Gray
}

Write-Host "=== Migration Removal Summary ===" -ForegroundColor Magenta
if ($successfulRemovals.Count -gt 0) {
    Write-Host "✅ Successful removals:" -ForegroundColor Green
    $successfulRemovals | ForEach-Object { Write-Host "   - $_" -ForegroundColor Green }
}
if ($failedRemovals.Count -gt 0) {
    Write-Host "❌ Failed removals:" -ForegroundColor Red
    $failedRemovals | ForEach-Object { Write-Host "   - $_" -ForegroundColor Red }
}

Write-Host "" -ForegroundColor Gray
Write-Host "# Example usage:" -ForegroundColor Cyan
Write-Host ".\Remove-Migration.ps1 -ServiceName catalog" -ForegroundColor Gray
Write-Host ".\Remove-Migration.ps1 -ServiceName customer -Providers @('postgres')" -ForegroundColor Gray

if ($failedRemovals.Count -gt 0) {
    exit 1
}

exit 0
